# compose.override.http.yaml — HTTP-only dev mode overlay.
#
# Usage:
#   docker compose -f compose.yaml -f compose.override.http.yaml up -d
#   (or: make dev)
#
# Replaces the TLS+JWT proxy with a simple HTTP-only NGINX that forwards
# to the frontend and backend containers without TLS or JWT validation.
# Injects X-User-Id: 1 / X-User-Role: admin so backend auth works.
#
# FOR LOCAL DEVELOPMENT ONLY — never use this in production.
#
# Access the stack at: http://localhost:8080

services:
  proxy:
    ports: !reset
      - "8080:80"
    environment: !reset {}
    volumes: !reset
      - ./proxy/proxy.dev.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    environment:
      COOKIE_SECURE: "false"   # allow HttpOnly cookies over plain HTTP in dev
      MEDIA_ROOT: /data/recordings
    volumes:
      - /tmp/sticky-dvr-poc/recordings:/data/recordings:ro
