# compose.poc.yaml — Full sticky-dvr proof-of-concept stack
#
# Includes all six services:
#   postgres, db-init, backend, frontend, proxy    (from this repo)
#   overseer  (sticky-recorder image: overseer + recorder + ffmpeg)
#   converter (sticky-refinery image: overseer + converter + ffmpeg)
#
# Data mounts rooted at /tmp/sticky-dvr-poc/:
#   recordings/   .ts and .mp4 files (overseer writes, converter reads)
#   overseer/     overseer.db, overseer.jsonl
#   converter/    refinery.db
#   postgres/     PostgreSQL data directory
#   certs/        TLS certs for proxy (copy from ./certs/ or run make dev-certs)
#
# Usage:
#   make dev-certs                                      # if certs not yet generated
#   cp certs/tls.{crt,key} /tmp/sticky-dvr-poc/certs/  # copy certs to data dir
#   docker compose -f compose.poc.yaml build            # build overseer + converter images
#   docker compose -f compose.poc.yaml up -d            # launch everything
#   docker compose -f compose.poc.yaml logs -f          # follow all logs
#   docker compose -f compose.poc.yaml down             # tear down

# All build contexts use the parent directory so both local repos
# (sticky-overseer, sticky-recorder, sticky-converter) are accessible.
x-parent-context: &parent-context
  context: ..
  # Dockerfile paths are relative to the parent context

services:

  # ─── infrastructure ───────────────────────────────────────────────────────

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme-admin
    volumes:
      - /tmp/sticky-dvr-poc/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-init:
    image: sticky-backend:latest
    entrypoint: ["/usr/local/bin/sticky-initdb"]
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_DSN: postgres://sticky:changeme@postgres:5432/sticky?sslmode=disable
      PG_ADMIN_USER: postgres
      PG_ADMIN_PASSWORD: changeme-admin

  # ─── sticky-dvr core ──────────────────────────────────────────────────────

  backend:
    image: sticky-backend:latest
    restart: unless-stopped
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      BACKEND_PORT: 8080
      DB_DSN: postgres://sticky:changeme@postgres:5432/sticky?sslmode=disable
      JWT_SECRET: poc-jwt-secret
      OVERSEER_URL: ws://overseer:8080/ws
      CONVERTER_URL: ws://converter:8080/ws
      THUMBNAILER_URL: ws://thumbnailer:8080/ws
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      MEDIA_ROOT: /data/recordings
    volumes:
      - /tmp/sticky-dvr-poc/recordings:/data/recordings:ro

  frontend:
    image: sticky-frontend:latest
    restart: unless-stopped

  proxy:
    image: sticky-proxy:latest
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      JWT_SECRET: poc-jwt-secret
    volumes:
      - /tmp/sticky-dvr-poc/certs:/etc/nginx/certs:ro

  # ─── file server (nginx autoindex of recordings dir) ─────────────────────

  fileserver:
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      - ./poc/fileserver.conf:/etc/nginx/conf.d/default.conf:ro
      - /tmp/sticky-dvr-poc/recordings:/data:ro

  # ─── recorder (sticky-overseer + sticky-recorder + ffmpeg) ────────────────

  overseer:
    build:
      context: ..
      dockerfile: sticky-dvr/poc/Dockerfile.recorder
    image: sticky-recorder:poc
    restart: unless-stopped
    volumes:
      # Custom config overrides the baked-in default
      - ./poc/overseer-config.yaml:/etc/sticky-overseer/config.yaml:ro
      # Persistent state (overseer.db, overseer.jsonl)
      - /tmp/sticky-dvr-poc/overseer:/data
      # Recordings directory (overseer writes .ts files here)
      # Nested mount: /data/recordings shadows /data for this subdirectory
      - /tmp/sticky-dvr-poc/recordings:/data/recordings
    # wget exits non-zero on HTTP 400, so use -S to capture response headers in stderr
    # The WS endpoint returns 400 Bad Request for plain HTTP — that IS healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qSO- http://localhost:8080/ws 2>&1 | grep -q '400 Bad Request'"]
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 3

  # ─── thumbnailer ──────────────────────────────────────────────────────────

  thumbnailer:
    build:
      context: ..
      dockerfile: sticky-dvr/poc/Dockerfile.thumbnailer
    image: sticky-thumbnailer:poc
    restart: unless-stopped
    volumes:
      - ./poc/thumbnailer-config.yaml:/data/config.yaml:ro
      - /tmp/sticky-dvr-poc/recordings:/recordings
      - /tmp/sticky-dvr-poc/thumbnailer:/data
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/openapi.json"]
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 3

  # ─── converter (sticky-overseer + sticky-refinery + ffmpeg) ───────────────

  converter:
    build:
      context: ..
      dockerfile: sticky-dvr/poc/Dockerfile.converter
    image: sticky-converter:poc
    restart: unless-stopped
    volumes:
      # Converter config (points paths at /recordings)
      - ./poc/converter-config.yaml:/data/config.yaml:ro
      # Read/write recordings: converter writes .mp4 output alongside .ts inputs
      - /tmp/sticky-dvr-poc/recordings:/recordings
      # Converter state (refinery.db)
      - /tmp/sticky-dvr-poc/converter:/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/openapi.json"]
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 3
